import expect from 'expect';
import { Type, EVar } from '../src/theory/tm';
import { Lam, Arr } from '../src/theory/lambda';
// import { Sigma } from '../src/theory/tuple';
import { empty as emptyCtx } from '../src/theory/context';

describe('typelevels', () => {
  const type = Type.singleton;

  // TODO these tests now seem very silly, since types are now instance
  // variables instead of being generated by getType. Get rid of them?
  it('knows the types of basics', () => {
    // special case!
    expect(type.type).toBe(null);
  });

  it('knows arrs', () => {
    expect(new Arr(type, type).type).toBe(type);
  });

  // it('knows sigmas', () => {
  //   // XXX what should the second part of a sigma be? is it a lambda?
  //   expect(new Sigma(type, new Lam('x', type)).getType(emptyCtx))
  //     .toBe(type);
  // });
});
