export const WIDGET_LOAD = 'WIDGET_LOAD';
export const WIDGET_LOAD_SUCCESS = 'WIDGET_LOAD_SUCCESS';
export const WIDGET_LOAD_FAIL = 'WIDGET_LOAD_FAIL';

export const AUTH_LOAD = 'AUTH_LOAD';
export const AUTH_LOAD_SUCCESS = 'AUTH_LOAD_SUCCESS';
export const AUTH_LOAD_FAIL = 'AUTH_LOAD_FAIL';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';

export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';

export const TOOLBOX_SEARCH = 'TOOLBOX_SEARCH';

export const NAME_CLICK = 'NAME_CLICK';

export const DEFINITION_RENAME = 'DEFINITION_RENAME';
